# Site settings 
title: "Akshit Arora" 
email: akshit.arora@colorado.edu
description: "Artificial Intelligence, Deep Learning and Photography" 
baseurl: "/carte-noire" 
url: "https://aroraakshit.github.io/carte-noire/" 
title_description: "I am a graduate student at <a href=\"https://www.colorado.edu/\">University of Colorado Boulder</a>. My main research interests are in the domain of Deep Learning and Machine Perception. I want to solve problems that connect human perception and mindsets using deep learning. <br><br><a href=\"about\">About</a> | <a href=\"akshit_cv.pdf\">Resume</a> | <a href=\"projects\">Projects</a>" 

title_image: "akshit.JPG" 
google_analytics: "UA-109066326-1" 
disqus_account: akshitarora-github-io 
github_repository: https://github.com/aroraakshit/carte-noire
addthis_id: ra-59f92e11f7baa2ae 
post_limit: 5 
author_name: "Akshit Arora"

# Social usernames/URLs
twitter_username: AkshitArora1995
github_username:  aroraakshit
instagram_username: akshit1995
reddit_username: 
linkedin_link: https://www.linkedin.com/in/aakshit/
google_plus_link:
stackoverflow_link: 
xing_link:
facebook_link: 
f500px_username: akshitarora
flickr_username: akshitarora

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> and modified by <a href=\"https://twitter.com/AkshitArora1995\">Akshit</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/aroraakshit/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
